SELECT 
  CONCAT(O.NAME, '(', SUBSTRING(O.OCCUPATION, 1, 1), ')') AS N
FROM OCCUPATIONS AS O 
ORDER BY N;

SELECT 
  CONCAT('There are a total of ', CAST(COUNT(O.OCCUPATION) AS VARCHAR), ' ', LOWER(O.OCCUPATION), 's.') 
FROM OCCUPATIONS AS O 
GROUP BY O.OCCUPATION
ORDER BY COUNT(O.OCCUPATION), O.OCCUPATION;